### ISSUE TITLE
Vendr 2.0 version?

### ISSUE THREAD

**Issue by HaydonGunn** [bjarnef/vendr-product-reviews#3]
Are there any plans to release a version of this package for Vendr 2.0 / Umbraco 9+? 
If so, would you know an ETA for this?

**Comment by bjarnef** [comment]
Yeah, I will probably look at making the package work on Vendr v2 / Umbraco v9 as well.
Not sure if the multi-target approach always will here, when using various part of the Vendr and Umbraco APIs.

I think @mattbrailsford would like to help with this and it could be a great use-case to test Vendr v2.

**Comment by mattbrailsford** [comment]
Hey all, I'm just in the process of porting Vendr.Checkout which I think will be a good indicator whether it's possible to multi target these types of packages, specifically where there are some front end views. I'll keep you posted, or you can keep and eye on the code for it here https://github.com/vendrhub/vendr-checkout/tree/feature/v2

Matt

**Comment by sashashev** [comment]
HI Matt. That link above is going to a 404. Just wondering if we are any closer to a V2 version?

**Comment by bjarnef** [comment]
@sashashev the branch was renamed to `v2/dev` which is now the default branch: https://github.com/vendrhub/vendr-checkout/

I have worked on a multi-target version in the current `v2/dev` branch https://github.com/vendrcontrib/vendr-reviews/tree/v2/dev which should work with Vendr 2.0 on both Umbraco 8 and 9. Still missing a few parts in code to make it work on both Umbraco versions and some testing of the package.

**Comment by stefanie27** [comment]
@bjarnef Thank you for your feedback. Can you please confirm if Vendr Reviews is working in Umbraco v9 yet? I used it in our project, but there are a couple of errors.

**Comment by bjarnef** [comment]
@stefanie27 the current Vendr Reviews package won't work on Umbraco v9 since it was built for .NET Framework and Umbraco now is running on .NET Core/.NET5, but the v2 of the package shouldn't be far away.

**Comment by sashashev** [comment]
HI Sorry to hassle but @bjarnef any updates on the reviews?

**Comment by bjarnef** [comment]
Hi all

Sorry for the long wait, but v2.0.0 is now available on https://our.umbraco.com/packages/website-utilities/vendr-reviews/ or as NuGet package https://www.nuget.org/packages/Vendr.contrib.reviews/

Note that Vendr 2.0 requires requires Umbraco 8.17.0+ or Umbraco 9.0.0+

Please let me know if you are experiencing some errors or have suggestions for improvement.

Happy holidays ⭐🎅🎄

**Comment by sashashev** [comment]
Thanks Bjarne,

That’s awesome.

Happy Holidays to you also.



Regards,

Sasha Shevelev
managing director

e ***@***.******@***.***>
m 0400 200 533

webcoda pty ltd
206/35 buckingham street, surry hills, nsw 2010

t +61 2 9370 3636
w www.webcoda.com.au<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.webcoda.com.au_&d=DwMF-g&c=fP4tf--1dS0biCFlB0saz0I0kjO5v7-GLPtvShAo4cc&r=iH7JK2kObAP31Dk9cji4IS2psNVQPXxMQfxrYWSg55w&m=DwJNi1ZW-6H7TvCfjEbhReQR0ISfl9pLwOa1NGSB4q4&s=gaK5jV0mhJSw9ygpaWEW8nEg5PiHLAxmOPBAct9w98E&e=>

Connect


CONFIDENTIALITY NOTICE
The information contained in this message is confidential, intended only for the use of the individual or the entity named as recipient. If the reader of this message is not that recipient, you are notified that any dissemination, distribution or copy of this message is strictly prohibited. If you have received this message in error, please immediately notify us by telephone on the number above. Your co-operation is appreciated.
